# vim ft=yaml
language: erlang
env:
 global:
 matrix:
before_install:
    # The ultimate one-liner setup for NeuroDebian repository
    - bash <(wget --no-check-certificate -q -O- https://raw.githubusercontent.com/neurodebian/neurodebian/master/tools/nd-configurerepo) -c software,data --overwrite --sources -f full
    # See what we have
    - sudo apt-cache policy
    # Install all build dependencies
    - travis_retry sudo apt-get build-dep afni
    # For some obnoxious reason it doesn't get installed
    - travis_retry sudo apt-get install libnifti-dev
install:
script:
    # build and run tests at once
    - mkdir build
    - cd build;  cmake -DBUILD_SHARED_LIBS:BOOL=ON ..;  make
